models/Category.php
<?php
/**
 * Created by PhpStorm.
 * User: Lenovo
 * Date: 26.05.2018
 * Time: 18:05
 */

namespace app\models;
use yii\db\ActiveRecord;


class Category extends ActiveRecord
{

    public function behaviors()
    {
        return [
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ]
        ];
    }

    public static function tableName(){
        return 'category';
    }

    public function getProducts(){
        return $this->hasMany(Product::className(), ['category_id' => 'id']);
    }


}

controllers/CartController.php
<?php
/**
 * Created by PhpStorm.
 * User: Lenovo
 * Date: 19.06.2018
 * Time: 13:12
 */

namespace app\controllers;
use app\models\Product;
use app\models\Cart;
use Yii;
use app\models\Order;
use app\models\OrderItems;

class CartController extends AppController
{
    public function actionAdd(){
        $id = Yii::$app->request->get('id');
        $qty = (int)Yii::$app->request->get('qty');
        $qty = !$qty ?  1 : $qty;

        //product is object we pass into the cart model
        $product = Product::findOne($id);
        if(empty($product)) return false;
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->addToCart($product, $qty);
        if(!Yii::$app->request->isAjax){
            return $this->redirect(Yii::$app->request->referrer);
        }
        $this->layout = false;
        return $this->render('cart-modal',[
            'session' => $session
        ]);
    }

    public function actionClear(){
        $session = Yii::$app->session;
        $session->open();
        $session->remove('cart');
        $session->remove('cart.qty');
        $session->remove('cart.sum');
        $this->layout = false;
        return $this->render('cart-modal',[
            'session' => $session
        ]);
    }

    public function actionDelItem(){
        $id = Yii::$app->request->get('id');
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->deleteItem($id);
        $this->layout = false;
        return $this->render('cart-modal',
            ['session' => $session]
        );
    }

    public function actionShow(){
        $session = Yii::$app->session;
        $session->open();
        $this->layout = false;
        return $this->render('cart-modal',['session' => $session]);
    }

    public function actionView(){
        //debug(Yii::$app->params['adminEmail']);die;
        $session = Yii::$app->session;
        $session->open();
        $this->setMeta('Cart');
        $order = new Order();
        if($order->load(Yii::$app->request->post())){

            $order->qty = $_SESSION['cart.qty'];
            $order->sum = $_SESSION['cart.sum'];
            if($order->save()){
                $this->saveOrderItems($session['cart'], $order->id);

                Yii::$app->mailer->compose('order',
                    ['session' => $session])
                    ->setFrom(['seymour.aliyev@yandex.ru' => 'Yii2'])
                    ->setTo($order->email)
                    ->setSubject('Order Response')
                    ->send();
                Yii::$app->session->setFlash('success','Order has been saved. Manager will contact u soon!');
                $session->remove('cart');
                $session->remove('cart.qty');
                $session->remove('cart.sum');
                return $this->refresh();
            } else {
                Yii::$app->session->setFlash('error','Ups. Order has not been saved');
            }
        }

        return $this->render('view',
        [
            'orderModel' => $order,
            'session' => $session
        ]);
    }

    protected function saveOrderItems($items, $order_id){

        foreach ($items as $id => $item) {
            $order_items = new OrderItems();
            $order_items->order_id = $order_id;
            $order_items->product_id = $id;
            $order_items->name = $item['name'];
            $order_items->price = $item['price'];
            $order_items->qty_item = $item['qty'];
            $order_items->sum_item = $item['qty'] * $item['price'];
            $order_items->save(false);
        }
    }


}

controllers/CategoryController.php
<?php
/**
 * Created by PhpStorm.
 * User: Lenovo
 * Date: 27.05.2018
 * Time: 20:39
 */

namespace app\controllers;
use app\models\Category;
use app\models\Product;
use Yii;
use yii\data\Pagination;

class CategoryController extends AppController
{

    public function actionIndex(){
        $hits = Product::find()->where(['hit' => 1])->limit(6)->all();
        $this->setMeta('E-SHOPPER');
        return $this->render('index',[
            'hits' => $hits
        ]);
    }

    public function actionView($id){
        $category = Category::findOne($id);
        if(empty($category)){
            throw new \yii\web\HttpException(404, 'The requested Category could not be found.');
        }

        $query = Product::find()->where(['category_id' => $id]);
        $pages = new Pagination(['totalCount' => $query->count(),'pageSize' => 3,
            'forcePageParam' => false, 'pageSizeParam' => false]);
        $products = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        $this->setMeta('E-SHOPPER | '.$category->name, $category->keywords, $category->description);
        return $this->render('view',[
            'products' => $products,
            'category' => $category,
            'pages' => $pages
        ]);
    }

    public function actionSearch(){
        $q = trim(Yii::$app->request->get('q'));

        $this->setMeta('E-SHOPPER | Search : '.$q);
        if(!$q){
            return $this->render('search');
        }
        $query = Product::find()->where(['like', 'name', $q]);
        $pages = new Pagination(['totalCount' => $query->count(),'pageSize' => 3,
            'forcePageParam' => false, 'pageSizeParam' => false]);
        $products = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();
        return $this->render('search',[
           'products' => $products,
           'pages' => $pages,
           'q' => $q
        ]);

    }

}

controllers/ProductController.php
<?php
/**
 * Created by PhpStorm.
 * User: Lenovo
 * Date: 07.06.2018
 * Time: 6:40
 */

namespace app\controllers;
use Yii;
use app\models\Category;
use  app\models\Product;


class ProductController extends AppController
{
    public function  actionView($id){
        $product = Product::findOne($id);
        if(empty($product)){
            throw new \yii\web\HttpException(404, 'The requested Product could not be found.');
        }
        $hits = Product::find()->where(['hit' => 1])->limit(5)->all();
        $this->setMeta('E-SHOPPER | '.$product->name, $product->keywords, $product->description);
        return $this->render('view',[
           'product' => $product,
           'hits' => $hits
        ]);
    }

}

views/category/search.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\LinkPager;

?>

<section id="advertisement">
    <div class="container">
        <img src="/images/shop/rek.jpg" alt="" />
    </div>
</section>

<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="left-sidebar">
                    <h2>Category</h2>

                    <ul class="catalog category-products">
                        <?= \app\components\MenuWidget::widget(['tpl' => 'menu'])?>
                    </ul>

                    <div class="brands_products"><!--brands_products-->
                        <h2>Brands</h2>
                        <div class="brands-name">
                            <ul class="nav nav-pills nav-stacked">
                                <li><a href=""> <span class="pull-right">(50)</span>Acne</a></li>
                                <li><a href=""> <span class="pull-right">(56)</span>Grüne Erde</a></li>
                                <li><a href=""> <span class="pull-right">(27)</span>Albiro</a></li>
                                <li><a href=""> <span class="pull-right">(32)</span>Ronhill</a></li>
                                <li><a href=""> <span class="pull-right">(5)</span>Oddmolly</a></li>
                                <li><a href=""> <span class="pull-right">(9)</span>Boudestijn</a></li>
                                <li><a href=""> <span class="pull-right">(4)</span>Rösch creative culture</a></li>
                            </ul>
                        </div>
                    </div><!--/brands_products-->

                    <div class="price-range"><!--price-range-->
                        <h2>Price Range</h2>
                        <div class="well">
                            <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
                            <b>$ 0</b> <b class="pull-right">$ 600</b>
                        </div>
                    </div><!--/price-range-->

                    <div class="shipping text-center"><!--shipping-->
                        <img src="/images/home/shipping.jpg" alt="" />
                    </div><!--/shipping-->

                </div>
            </div>

            <div class="col-sm-9 padding-right">
                <div class="features_items">
                    <h2 class="title text-center">Search result : <?=Html::encode($q)?></h2>
                    <?php if (!empty($products)) {?>
                        <?php
                            $i = 0;
                            foreach ($products as $product) {?>
                            <div class="col-sm-4">
                                <div class="product-image-wrapper">
                                    <div class="single-products">
                                        <div class="productinfo text-center">
                                            <?= Html::img("@web/images/products/{$product->img}", ['alt' => $product->name]) ?>
                                            <h2>$<?=$product->price;?></h2>


                                            <p>
                                                <a href="<?=Url::toRoute(['product/view','id'=> $product->id]);?>">
                                                    <?=$product->name;?>
                                                </a>
                                            </p>
                                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                        </div>
                                        <!--<div class="product-overlay">
                                            <div class="overlay-content">
                                                <h2>$<?/*=$product->price;*/?></h2>
                                                <p><?/*=$product->name;*/?></p>
                                                <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>-->
                                        <?php if($product->new):?>
                                            <?= Html::img("@web/images/home/new.png",['alt' => 'new','class' => 'new']) ?>
                                        <?php endif;?>
                                        <?php if($product->sale):?>
                                            <?= Html::img("@web/images/home/sale.png",['alt' => 'sale','class' => 'new']) ?>
                                        <?php endif;?>
                                    </div>
                                    <div class="choose">
                                        <ul class="nav nav-pills nav-justified">
                                            <li><a href=""><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                                            <li><a href=""><i class="fa fa-plus-square"></i>Add to compare</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <?php $i++;?>
                                <?php if($i % 3 == 0){ ?>
                                    <div class="clearfix"></div>
                                <?php } ?>
                        <?php }
                        ?>
                        <div class="clearfix"></div>
                        <?php
                            echo LinkPager::widget([
                                'pagination' => $pages,
                            ]);
                        ?>

                    <?php } else { ?>
                        <h2>Nothing was founded</h2>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</section>

views/category/view.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\LinkPager;

?>

<section id="advertisement">
    <div class="container">
        <img src="/images/shop/rek.jpg" alt="" />
    </div>
</section>

<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="left-sidebar">
                    <h2>Category</h2>

                    <ul class="catalog category-products">
                        <?= \app\components\MenuWidget::widget(['tpl' => 'menu'])?>
                    </ul>

                    <div class="brands_products"><!--brands_products-->
                        <h2>Brands</h2>
                        <div class="brands-name">
                            <ul class="nav nav-pills nav-stacked">
                                <li><a href=""> <span class="pull-right">(50)</span>Acne</a></li>
                                <li><a href=""> <span class="pull-right">(56)</span>Grüne Erde</a></li>
                                <li><a href=""> <span class="pull-right">(27)</span>Albiro</a></li>
                                <li><a href=""> <span class="pull-right">(32)</span>Ronhill</a></li>
                                <li><a href=""> <span class="pull-right">(5)</span>Oddmolly</a></li>
                                <li><a href=""> <span class="pull-right">(9)</span>Boudestijn</a></li>
                                <li><a href=""> <span class="pull-right">(4)</span>Rösch creative culture</a></li>
                            </ul>
                        </div>
                    </div><!--/brands_products-->

                    <div class="price-range"><!--price-range-->
                        <h2>Price Range</h2>
                        <div class="well">
                            <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
                            <b>$ 0</b> <b class="pull-right">$ 600</b>
                        </div>
                    </div><!--/price-range-->

                    <div class="shipping text-center"><!--shipping-->
                        <img src="/images/home/shipping.jpg" alt="" />
                    </div><!--/shipping-->

                </div>
            </div>

            <div class="col-sm-9 padding-right">
                <div class="features_items">
                    <h2 class="title text-center"><?=$category->name;?></h2>
                    <?php if (!empty($products)) {?>
                        <?php
                            $i = 0;
                            foreach ($products as $product) {?>
                            <div class="col-sm-4">
                                <div class="product-image-wrapper">
                                    <div class="single-products">
                                        <div class="productinfo text-center">
                                            <?= Html::img("@web/images/products/{$product->img}", ['alt' => $product->name]) ?>
                                            <h2>$<?=$product->price;?></h2>


                                            <p>
                                                <a href="<?=Url::toRoute(['product/view','id'=> $product->id]);?>">
                                                    <?=$product->name;?>
                                                </a>
                                            </p>
                                            <a data-id="<?=$product->id;?>" href="<?=Url::to(['/cart/add','id' => $product->id]);?>" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                        </div>
                                        <!--<div class="product-overlay">
                                            <div class="overlay-content">
                                                <h2>$<?/*=$product->price;*/?></h2>
                                                <p><?/*=$product->name;*/?></p>
                                                <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>-->
                                        <?php if($product->new):?>
                                            <?= Html::img("@web/images/home/new.png",['alt' => 'new','class' => 'new']) ?>
                                        <?php endif;?>
                                        <?php if($product->sale):?>
                                            <?= Html::img("@web/images/home/sale.png",['alt' => 'sale','class' => 'new']) ?>
                                        <?php endif;?>
                                    </div>
                                    <div class="choose">
                                        <ul class="nav nav-pills nav-justified">
                                            <li><a href=""><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                                            <li><a href=""><i class="fa fa-plus-square"></i>Add to compare</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <?php $i++;?>
                                <?php if($i % 3 == 0){ ?>
                                    <div class="clearfix"></div>
                                <?php } ?>
                        <?php }
                        ?>
                        <div class="clearfix"></div>
                        <?php
                            echo LinkPager::widget([
                                'pagination' => $pages,
                            ]);
                        ?>

                    <?php } else { ?>
                        <h2>Not products yet</h2>
                    <?php } ?>

                   <!-- <ul class="pagination">
                        <li class="active"><a href="">1</a></li>
                        <li><a href="">2</a></li>
                        <li><a href="">3</a></li>
                        <li><a href="">&raquo;</a></li>
                    </ul>-->
                </div>
            </div>
        </div>
    </div>
</section>